[project]
name = "steam-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cachetools>=6.2.0",
    "fastapi>=0.116.1",
    "gunicorn>=23.0.0",
    "requests>=2.32.5",
    "uvicorn>=0.35.0",
]
